### PR TITLE
Update addon via `ember init`

### PR DESCRIPTION
**Pull request by elwayman02**
Additionally, remove extraneous dependencies, such as all bower and most npm packages.

### CODE REVIEW

**Comment by monadichq** [comment]
LGTM! Thanks @elwayman02! Just out of curiosity, should I be removing these extraneous dependencies from all of my addons?

**Comment by jasonkriss** [comment]
LGTM! Thanks @elwayman02! Just out of curiosity, should I be removing these extraneous dependencies from all of my addons?

**Comment by elwayman02** [comment]
@jasonkriss it depends on what the addon is doing.  In this case, the addon doesn't actually do anything with Ember whatsoever; it merely runs an ember-cli blueprint. So you don't really need most of the other dependencies, which are for addons that will actually run within an Ember application (ie components, mixins, services, etc).

**Comment by jasonkriss** [comment]
gotcha. makes sense. Thanks @elwayman02!

**Pull request merged**
